name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Pre-download Maven dependencies
        run: |
          mvn dependency:go-offline

      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Run tests during build
        run: |
          docker compose run --rm --entrypoint mvn app verify

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker compose -f docker-compose.yml down