name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          docker-compose exec app mvn verify

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.yml down